server {
    listen 80;
    server_name localhost;

    # Set root directory
    root /var/www/html;

    # Set index file
    index index.php;

    # Standard location block
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Pass PHP scripts to FastCGI server
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000; # 'app' is the service name of the PHP container
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # Deny access to .htaccess files
    location ~ /\.ht {
        deny all;
    }
}
